### ISSUE TITLE
link to Developer Certificate of Origin is broken on the web

### ISSUE THREAD

**Issue by aaronkaplan** [ail-project/ail-website#2]
https://www.ail-project.org/Developer%20Certificate%20of%20Origin gives a 404.

(see the bottom of the main web page)

Another link that is broken : on the main website: [extensible Python-based framework](https://github.com/ail-project/ail-framework))
--> spot the error ? Two closing brakets  end up as the link "https://github.com/ail-project/ail-framework)"

**Comment by adulau** [comment]
Thank you.
