### ISSUE TITLE
Missing "Developer Certificate of Origin", links give 404

### ISSUE THREAD

**Issue by atluxity** [ail-project/ail-website#4]
Your index.html states "No CLA to sign, it's a simple [Developer Certificate of Origin](https://www.ail-project.org/Developer%20Certificate%20of%20Origin). Join us!" - but the link results in 404, and I can not see it mentioned in the website github repo.

https://github.com/ail-project/ail-website/blob/4d85efe9b15c3bd1228467e9b3c38fd72b5a042b/index.html#L43C163-L43C203

**Comment by adulau** [comment]
Good point Hans-Petter! It's fixed. https://github.com/ail-project/ail-website/commit/7b35a426641fafc49da7d337e56776b1bcd45d3e Thank you.
